accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^login/$',views.my_login,name='login'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^change_password/$',views.change_pass,name='change_pass'),
    url(r'^forget_password/$',views.forget_password,name='forget_password'),
]

cv/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

urlpatterns=[
    url(r'^base_info/$',views.base_info_view,name='base_info_no_para'),
    url(r'^base_info/(?P<id>[0-9]+)/(?P<pro>[0-9]+)/$',views.base_info_view,name='base_info'),
    url(r'^education_info/$',views.education_info_view,name='education_info'),
    url(r'^work_info/$',views.work_info_view,name='work_info'),
]

jobs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views
from cv.views import partpdf,interviewpdf
urlpatterns = [
    url(r'^admin/cv/base_info/partpdf/(?P<id>[0-9]+)/$',partpdf,name='partpdf'),
    url(r'^admin/cv/base_info/interviewpdf/(?P<id>[0-9]+)/$',interviewpdf,name='interviewpdf'),
    url(r'^admin/', admin.site.urls),
    url(r'^duals/',include('duals.urls',namespace='duals')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^cv/',include('cv.urls',namespace='cv')),
    url(r'^interview/',include('interview.urls',namespace='interview')),
    url(r'^schools-autocomplete/$',views.schoolsAutocomplete.as_view(),name='schools-autocomplete'),
    url(r'^position_category-autocomplete/$',views.position_categoryAutocomplete.as_view(),name='position_category-autocomplete'),
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#This is not suitable for production use!
admin.site.site_header = '招聘系统后台管理'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class provience(models.Model):
    name=models.CharField('分校',max_length=5)
    def __str__(self):
        return  self.name
    class Meta:
        verbose_name='分校'
        verbose_name_plural='分校管理'

class department(models.Model):
    name=models.CharField("部门",max_length=20)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='部门'
        verbose_name_plural='部门管理'
class my_authority(models.Model):
    admin_user=models.OneToOneField(User,on_delete=models.CASCADE)
    admin_authority_dep=models.ManyToManyField(department,verbose_name="部门")
    admin_authority_pro=models.ManyToManyField(provience,verbose_name="分校")
    def __str__(self):
        return self.admin_user.username
    def getdep(self):
        return ','.join([obj.name for obj in self.admin_authority_dep.all()])
    getdep.short_description='部门权限'
    def getpro(self):
        return ','.join([obj.name for obj in self.admin_authority_pro.all()])
    getpro.short_description='分校权限'
    class Meta:
        verbose_name='权限'
        verbose_name_plural='权限管理'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate
from django.utils.translation import ugettext, ugettext_lazy as _
import re
class my_authorityForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(my_authorityForm, self).__init__(*args, **kwargs)
        self.fields['admin_user'].queryset = User.objects.filter(is_staff=True)
class LoginForm(forms.Form):
    username = forms.CharField(
        label='用户名', required=True,
        error_messages={'required': '请填写您的用户名'}, widget=forms.TextInput(attrs={'placeholder': '用户名'}))
    password = forms.CharField(
        label='密码', required=False, widget=forms.PasswordInput())
    def clean_username(self):
        username = self.cleaned_data["username"]
        if not User.objects.filter(username=username):
            raise forms.ValidationError("用户名不存在")
        return username


class ChangeForm(forms.Form):
    password = forms.CharField(
        error_messages={'required': '请输入密码', 'max_length': '最多只能输入20个字符', 'min_length': '至少输入6个字符'},
        label='密码', required=True, max_length=20, widget=forms.PasswordInput(attrs={'placeholder': '长度在6~20个字符以内'}))
    confirm_password = forms.CharField(
        error_messages={'required': '请输入密码', 'max_length': '最多只能输入20个字符', 'min_length': '至少输入6个字符'},
        label='确认密码', required=True, max_length=20, min_length=6,
        widget=forms.PasswordInput(attrs={'placeholder': '长度在6~20个字符以内'}))
    class Meta:
        model = get_user_model()
        fields = ("password",)
    def clean_confirm_password(self):
        #cleaned_data=super(SignupForm,self).clean()
        password = self.cleaned_data.get("password",False)
        confirm_password = self.cleaned_data["confirm_password"]
        if  not( password == confirm_password):
            raise forms.ValidationError("确认密码和密码不一致")
        else:
            return confirm_password
    
def lowercase_email(email):
        """
        Normalize the address by lowercasing the domain part of the email
        address.
        """
        email = email or ''
        try:
            email_name, domain_part = email.strip().rsplit('@', 1)
        except ValueError:
            pass
        else:
            email = '@'.join([email_name.lower(), domain_part.lower()])
        return email

class SignupForm (forms.ModelForm):
    
    username =forms.CharField( 
        label='用户名',required=True,error_messages={'required': '请填写你的用户名','max_length':'最多只能输入15个字符','min_length':'至少输入3个字符'},max_length=15,min_length=3,widget=forms.TextInput(attrs={'placeholder':'3~15位字母/数字/汉字'}))
    email = forms.EmailField( error_messages={'required': '请填写你的email','invalid':'email格式不正确'},
        label='邮箱',required=True,widget=forms.EmailInput(attrs={'placeholder':'填写正确的email以方便您能通过邮箱找回密码'}))
    password =forms.CharField( error_messages={'required': '请输入密码','max_length':'最多只能输入20个字符','min_length':'至少输入6个字符'},
        label='密码',required=True,max_length=20,widget = forms.PasswordInput(attrs={'placeholder':'长度在6~20个字符以内'}))
    confirm_password= forms.CharField(error_messages={'required': '请输入密码','max_length':'最多只能输入20个字符','min_length':'至少输入6个字符'},
        label='确认密码',required=True,max_length=20,min_length=6,widget = forms.PasswordInput(attrs={'placeholder':'长度在6~20个字符以内'}))
    
    class Meta:
        model = get_user_model()
        fields = ("username","email","password",)
                                

    def clean_email(self):
        UserModel = get_user_model()
        email=self.cleaned_data["email"]
        lower_email=lowercase_email(email)
        try:
            UserModel._default_manager.get(email=lower_email)
        except UserModel.DoesNotExist:
            return lower_email
        raise forms.ValidationError("有人已经注册了这个email地址")
    
    def clean_confirm_password(self):
        #cleaned_data=super(SignupForm,self).clean()
        password = self.cleaned_data.get("password",False)
        confirm_password = self.cleaned_data["confirm_password"]
        if  not( password == confirm_password):
            raise forms.ValidationError("确认密码和密码不一致")
        return confirm_password
    
        
    
    def clean_username(self):
        UserModel = get_user_model()
        username = self.cleaned_data["username"]
        #过滤用户名敏感词的注册用户
        n=re.sub('[^\u4e00-\u9fa5a-zA-Z]','',username)
        
        mgc=['admin']        
        
        if n in mgc:
            raise forms.ValidationError("这么好的用户名当然被人提前预定啦，换一个试试^-^")
    
        try:
            UserModel._default_manager.get(username = username)
    
        except UserModel.DoesNotExist:
            return username
        raise forms.ValidationError("有人已经注册了这个用户名")
class ForgetPasswordForm(forms.Form):
    username =forms.CharField( label='用户名',required=True,error_messages={'required': '请填写你的用户名','max_length':'最多只能输入15个字符','min_length':'至少输入3个字符'},max_length=15,min_length=3,widget=forms.TextInput(attrs={'placeholder':'3~15位字母/数字/汉字'}))
    email = forms.EmailField( error_messages={'required': '请填写你的email','invalid':'email格式不正确'},label='邮箱',required=True,widget=forms.EmailInput(attrs={'placeholder':'填写你注册时使用的email'}))
    class Meta:
        model = get_user_model()
        fields = ("username","email","password",)
    def clean_email(self):
        UserModel = get_user_model()
        email=self.cleaned_data["email"]
        username = self.cleaned_data["username"]
        lower_email=lowercase_email(email)
        try:
            UserModel._default_manager.get(email=lower_email,username = username)
            return email
        except UserModel.DoesNotExist:
            raise forms.ValidationError("用户名或email地址有误")

accounts/views.py
from django.shortcuts import render,redirect
from .forms import *
# Create your views here.
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponse,HttpResponseRedirect
from random import choice
import string
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password
from django.urls import reverse
from jobs import settings
import xlrd
# from duals.models import *
from django.contrib import messages
def my_login(request):
    redirect_to = request.GET.get('next')
    if  not redirect_to:
        redirect_to=reverse('post:show_positions')
    if request.method == 'POST':
        form = LoginForm(data=request.POST, auto_id="%s")
        if form.is_valid():
            data = form.clean()
            user = authenticate(request,username=data['username'].strip(), password=data['password'])
#             bk = xlrd.open_workbook('学校码表.xlsx')
#             sh = bk.sheet_by_name('学校')
#             nrows = sh.nrows
#             for i in range(1, nrows):
#                 name = sh.cell_value(i, 0)
#                 pc = sh.cell_value(i, 3)
#                 try:
#                     schools.objects.create(name=name,pc=pc)
#                 except BaseException as e:
#                     print (e)
#             print ('finished!')
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(redirect_to)
            else:
                login_errors='密码有误'
    else:
        form = LoginForm(auto_id="%s")
    return render(request, 'accounts/login.html', locals())
def signup(request):
    redirect_to = request.GET.get('next')
    if not redirect_to or redirect_to==reverse('accounts:login'):
        redirect_to=reverse('post:show_positions')
    path=request.get_full_path()
    if request.method=='POST':
        form=SignupForm(data=request.POST,auto_id="%s")
        if form.is_valid():
            UserModel=get_user_model()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user=UserModel.objects.create_user(username=username,email=email,password=password)
            user.save()
            auth_user = authenticate(username=username,password=password)
            login(request,auth_user)
            messages.add_message(request, messages.INFO, '账号注册成功！')
            return HttpResponseRedirect(redirect_to)
    else:
        form=SignupForm(auto_id="%s")
    return render(request,'accounts/signup.html',locals())
def logout_view(request):
    logout(request)
    return redirect(reverse('accounts:login'))
def change_pass(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form= ChangeForm(request.POST)
            if form.is_valid():
                confirm_password = form.clean_confirm_password()
                User.objects.filter(username=request.user.username).update(password=make_password(confirm_password))  ##如果用户名、原密码匹配则更新密码
                return redirect(reverse('accounts:login'))
        else:
            form = ChangeForm()
        return render(request,'accounts/change.html', locals())
    else:
        return redirect(reverse('accounts:login'))
def GenPassword(length=8,chars=string.ascii_letters+string.digits):
    return ''.join([choice(chars) for i in range(length)])
def forget_password(request):
    if request.method == 'POST':
            form= ForgetPasswordForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                email= form.clean_email()
                password=GenPassword(8)
                try:
                    send_mail('密码重置', '您好,您的密码重置为{0}，请登录后及时更改密码！'.format(password), settings.DEFAULT_FROM_EMAIL,[email], fail_silently=False)
                    User.objects.filter(username=username).update(password=make_password(password))  ##如果用户名、原密码匹配则更新密码
                except:
                    warning_message='密码重置失败，请联系管理员！'
                warning_message='密码重置成功，请注意查收您的邮箱！'
    else:
        form = ForgetPasswordForm()
    return render(request,'accounts/getpassword.html', locals())

accounts/templates/accounts/change.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}
  <div align="center" class="container pt">
	<form class="form-horizontal" id = "form" action="{{path}}" method="post">
                {% csrf_token %}
                
      
                <div class="form-group {%if form.password.errors%} has-error {%endif%}">
                  <label for="pssword" class="col-sm-4 control-label">新密码*:</label>
                  <div class="col-sm-5">
                    {{form.password}}
                  </div>
                  {%if form.password.errors%}
                  <div class="col-sm-5 col-sm-offset-4 margint10">
                  <span class="color-background2 ">
                  {% for error in form.password.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>
                <div class="form-group {%if form.password2.errors%} has-error {%endif%}">
                  <label for="pssword2" class="col-sm-4 control-label">确认新密码*:</label>
                  <div class="col-sm-5">
                    {{form.confirm_password}}
                  </div>
                  {%if form.confirm_password.errors%}
                  <div class="col-sm-5 col-sm-offset-4 margint10">
                  <span class="color-background2 ">
                  {% for error in form.confirm_password.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>

                <div class="form-group margint30">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">确认</button>
                  </div>
                </div>
               </form>
  </div>
{% endblock %}

accounts/templates/accounts/getpassword.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}
  <div align="center">
	<form  action="{{path}}" method="post">
                {% csrf_token %}
                
      
                <div>
                  <label>用户名*:</label>
                  <div>
                    {{form.username}}
                  </div>
                  {%if form.username.errors%}
                  <div>
                  <span>
                  {% for error in form.username.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>
                <div >
                  <label>电子邮箱*:</label>
                  <div >
                    {{form.email}}
                  </div>
                  {%if form.email.errors%}
                  <div >
                  <span >
                  {% for error in form.email.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>

                <div >
                  <div >
                    <button type="submit">确认</button>
                  </div>
                </div>
               </form>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}

  <div align="center" class="container pt">
    <form class="form-horizontal" id = "form" action="./?next={{redirect_to}}" method="post">
                {% csrf_token %}
                        
                        
                  <div>
                    <label >用户名* :</label>
                    <div>
                    {{form.username}}
                    </div>
                    {%if form.username.errors%}
                      <div>
                        <span>
                        {% for error in form.username.errors %}
                          {{ error|escape }}
                        {% endfor %}
                        </span>
                      </div>
                    {%endif%}
                 </div>
                
                <div>
                  <label>密码*:</label>
                  <div>
                    {{form.password}}
                  </div>
                  {%if form.password.errors%}
                  <div>
                    <span>
                    {% for error in form.password.errors %}
                      {{ error|escape }}
                    {% endfor %}
                    </span>
                  </div>
                  {%endif%}
                </div>
                

                <div>
                  <div>
                    <button type="submit">确认</button>
                    <a href="{% url 'accounts:forget_password' %}"><span>忘记密码</span></a>
                  </div>
                </div>
                <div>
                  {{login_errors}}
                </div>
               </form>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}

<div align="center" class="container pt">
	<form class="form-horizontal" id = "form" action="./?next={{redirect_to}}" method="post">
                {% csrf_token %}
                  <div class="form-group {%if form.username.errors%} has-error {%endif%}">
                    <label for="username" class="col-sm-4 control-label">用户名* :</label>
                    <div class="col-sm-5">
                    {{form.username}}
                    </div>
                    {%if form.username.errors%}
                  <div class="col-sm-5 col-sm-offset-4 margint10">
                  <span class="color-background2 ">
                  {% for error in form.username.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>
      			<div class="form-group {%if form.username.errors%} has-error {%endif%}">
                    <label for="username" class="col-sm-4 control-label">电子邮箱* :</label>
                    <div class="col-sm-5">
                    {{form.email}}
                    </div>
                    {%if form.email.errors%}
                  <div class="col-sm-5 col-sm-offset-4 margint10">
                  <span class="color-background2 ">
                  {% for error in form.email.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>
                <div class="form-group {%if form.password.errors%} has-error {%endif%}">
                  <label for="pssword" class="col-sm-4 control-label">密码*:</label>
                  <div class="col-sm-5">
                    {{form.password}}
                  </div>
                  {%if form.password.errors%}
                  <div class="col-sm-5 col-sm-offset-4 margint10">
                  <span class="color-background2 ">
                  {% for error in form.password.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>
                <div class="form-group {%if form.password2.errors%} has-error {%endif%}">
                  <label for="pssword2" class="col-sm-4 control-label">确认密码*:</label>
                  <div class="col-sm-5">
                    {{form.confirm_password}}
                  </div>
                  {%if form.confirm_password.errors%}
                  <div class="col-sm-5 col-sm-offset-4 margint10">
                  <span class="color-background2 ">
                  {% for error in form.confirm_password.errors %}
                    {{ error|escape }}
                  {% endfor %}
                  </span>
                  </div>
                  {%endif%}
                </div>

                <div class="form-group margint30">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">确认</button>
                  </div>
                </div>
               </form>
               </div>
{% endblock %}