cv/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

urlpatterns=[
    url(r'^base_info/$',views.base_info_view,name='base_info_no_para'),
    url(r'^base_info/(?P<id>[0-9]+)/(?P<pro>[0-9]+)/$',views.base_info_view,name='base_info'),
    url(r'^education_info/$',views.education_info_view,name='education_info'),
    url(r'^work_info/$',views.work_info_view,name='work_info'),
]

jobs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views
from cv.views import partpdf,interviewpdf
urlpatterns = [
    url(r'^admin/cv/base_info/partpdf/(?P<id>[0-9]+)/$',partpdf,name='partpdf'),
    url(r'^admin/cv/base_info/interviewpdf/(?P<id>[0-9]+)/$',interviewpdf,name='interviewpdf'),
    url(r'^admin/', admin.site.urls),
    url(r'^duals/',include('duals.urls',namespace='duals')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^cv/',include('cv.urls',namespace='cv')),
    url(r'^interview/',include('interview.urls',namespace='interview')),
    url(r'^schools-autocomplete/$',views.schoolsAutocomplete.as_view(),name='schools-autocomplete'),
    url(r'^position_category-autocomplete/$',views.position_categoryAutocomplete.as_view(),name='position_category-autocomplete'),
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#This is not suitable for production use!
admin.site.site_header = '招聘系统后台管理'

post/urls.py
# urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.show_positions,name='show_positions'),
    url(r'^property=(?P<pro>[a-z]+)$', views.show_positions,name='show_positions'),
    url(r'^category=(?P<cat>[0-9]+)$', views.show_positions,name='show_positions'),
    url(r'^category=(?P<cat>[0-9]+)property=(?P<pro>[a-z]+)$', views.show_positions,name='show_positions'),
    #url(r'^property=(?P<pro>[a-z]+)/category=(?P<cat>[0-9]+)$', views.show_positions,name='show_positions'),
    url(r'^(?P<id>[0-9]+)/$',views.show_proviences,name='show_pro'),
    url(r'^(?P<id>[0-9]+)/(?P<pro>[0-9]+)/$',views.to_cv,name='to_cv'),
]

post/models.py
from django.db import models
from accounts.models import provience,department
from django.contrib.auth.models import User
from random import choice
# Create your models here.
pos_choice=(('a','全职'),('b','兼职'),('c','实习'))
class position_category(models.Model):
    name=models.CharField('岗位类别',max_length=20)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='岗位类别'
        verbose_name_plural='岗位类别管理'
class positions(models.Model):
    name=models.CharField('岗位名称',max_length=20)
    dep=models.ManyToManyField(department,verbose_name="招聘部门")
    pro=models.ManyToManyField(provience,verbose_name="招聘省份")
    position_requirements=models.TextField('岗位要求',max_length=500)
    position_statement=models.TextField('岗位描述',max_length=500)
    position_annual_salay_up=models.PositiveIntegerField('年薪上限',null=True,blank=True)
    position_annual_salay_down=models.PositiveIntegerField('年薪下限',null=True,blank=True)
    position_monthly_salary_up=models.PositiveIntegerField('月薪上限',null=True,blank=True)
    position_monthly_salary_down=models.PositiveIntegerField('月薪下限',null=True,blank=True)
    recruiting_numbers=models.PositiveSmallIntegerField('招聘人数')
    category=models.ForeignKey(position_category,verbose_name='岗位类别')
    property=models.CharField('岗位性质',max_length=1,choices=pos_choice,default='a')
    post_status=models.BooleanField('发布状态')
    sort_value=models.PositiveSmallIntegerField('显示顺序',default=0)
    update_date=models.DateTimeField('更新时间',auto_now_add=True,editable=True)
    def __str__(self):
        return self.name
    def getdep(self):
        return ','.join([obj.name for obj in self.dep.all()])
    getdep.short_description='招聘部门'
    def getpro(self):
        if len(self.pro.all())>30:
            return '全国(西藏、港澳台除外）'
        else:
            return ','.join([obj.name for obj in self.pro.all()])
    getpro.short_description='招聘省份'
    class Meta:
        verbose_name='岗位发布'
        verbose_name_plural='岗位发布管理'

post/forms.py
from dal import autocomplete
from django.forms import ModelForm
from .models import *

class positionsForm(ModelForm):
    class Meta:
        model = positions
        exclude = ('',)
#         widgets = {
#             'category':autocomplete.ModelSelect2(url='position_category-autocomplete'),
#         }

post/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
# Create your views here.
from django.views.generic import ListView
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.http import HttpResponse

num_each_page=20

def show_positions(request,pro='d',cat=100):
    pc=position_category.objects.all()
    cat=int(cat)
    if pro=='d':
        mes_list = positions.objects.filter(post_status=True)
    else:
        mes_list = positions.objects.filter(property=pro).filter(post_status=True)
    if cat==100:
        mes_list=mes_list.order_by('-sort_value')
    else:
        mes_list=mes_list.filter(category=cat).order_by('-sort_value')
    paginator = Paginator(mes_list, num_each_page)
    page = request.GET.get('page')
    try:
        mes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        mes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        mes = paginator.page(paginator.num_pages)
    return render(request, 'post/positions_list.html', locals())
def show_proviences(request,id):
    position=positions.objects.filter(pk=id).filter(post_status=True).order_by('-sort_value')
    ptest='hello'
    return render(request,'post/proviences.html',locals())
    #return redirect(reverse('cv:base_info',kwargs={'id':id}))
# def to_cv(request,id,pro):
#     return redirect(reverse('cv:base_info', kwargs={'id': id,'pro':pro}))
def to_cv(request,id,pro):
    return redirect(reverse('cv:base_info', kwargs={'id': id,'pro':pro}))

post/templates/post/positions_list.html
{% extends "base.html" %}
{% load humanize %}
{% load  staticfiles %}
{% block content %}

  <div align="center"  class="container" >
    <script type="text/javascript">
        var ua = navigator.userAgent;
        var ipad = ua.match(/(iPad).*OS\s([\d_]+)/),
            isIphone = !ipad && ua.match(/(iPhone\sOS)\s([\d_]+)/),
            isAndroid = ua.match(/(Android)\s+([\d.]+)/),
            isMobile = isIphone || isAndroid;
            if(isMobile) {
              document.write("<p>为保证网页显示效果，请您横屏查看本网页</p>");
            }
    </script>
  	<div ><p> 招聘岗位</p></div>
	<div align="left" class="col-lg-10">
	<table class="table table-striped table-bordered">
	<tr>
	<th>岗位名称</th>
	<th>岗位类别</th>
	<th>招聘部门</th>
	<th>工作地点</th>
	<th>月薪范围（元）</th>
	<th>年薪范围（元）</th>
	<th>岗位要求</th>
	<th>岗位描述</th>
	<th>招聘人数</th>
	<th>岗位性质</th>
	<th>更新时间</th>
	<th>投递简历</th>
	</tr>
	{% for m in mes%}
		<tr onmouseover="this.style.backgroundColor='#ffff66';" onmouseout="this.style.backgroundColor='#d4e3e5';">
			<td>{{m.name}}</td>
			<td>{{m.category}}</td>
			<td>{{m.getdep}}</td>
			<td>{{m.getpro }}</td>
			<td>{{m.position_monthly_salary_down |intcomma:False}}--{{m.position_monthly_salary_up |intcomma:False}}</td>
			<td>{{m.position_annual_salay_down |intcomma:False}}--{{m.position_annual_salay_up |intcomma:False}}</td>
			<td>{{m.position_requirements}}</td>
			<td>{{m.position_statement}}</td>
			<td>{{m.recruiting_numbers }}</td>
			<td>{{m.get_property_display}}
			<td>{{m.update_date|date:"Y-m-d H:i:s"}}</td>
			<td><a href="{{m.id}}"  target="_black">投递</a></td>
		</tr>
	{%endfor%}
	</table>
	</div>
	<div class="col-lg-2">
		<p><font size=2>按照岗位性质筛选</font></p>
			<a href="category={{cat}}property=d">全部</a><br/>
			<a href="category={{cat}}property=a">全职</a><br/>
			<a href="category={{cat}}property=b">兼职</a><br/>
			<a href="category={{cat}}property=c">实习</a><br/>
		<p></p>
		<p><font size=2>按照岗位类别筛选</font></p>
			<a href="category=100property={{pro}}">全部</a><br/>
			{% for p in pc %}
				<a href="category={{p.id}}property={{pro}}">{{p.name}}</a><br/>
			{% endfor %}

	</div>
	<div class="pagination">
    	<span class="step-links">
        	{% if mes.has_previous %}
           		<a href="?page={{ mes.previous_page_number }}">上一页</a>
        	{% endif %}

        	<span class="current">
           	 	第{{ mes.number }}页  共{{ mes.paginator.num_pages }}页.
        	</span>

        	{% if mes.has_next %}
            	<a href="?page={{ mes.next_page_number }}">下一页</a>
        	{% endif %}
    	</span>
	</div>
  </div>
{% endblock %}

post/templates/post/proviences.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}
	<div class="container pt">
		<p>请选择意向工作地点</p>
		{% for pos in position %}
			{% for pp in pos.pro.all %}
					<a href="{{pp.id}}">{{pp}}</a><br/>
			{% endfor %}
		{% endfor %}
	</div>
{% endblock %}