cv/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

urlpatterns=[
    url(r'^base_info/$',views.base_info_view,name='base_info_no_para'),
    url(r'^base_info/(?P<id>[0-9]+)/(?P<pro>[0-9]+)/$',views.base_info_view,name='base_info'),
    url(r'^education_info/$',views.education_info_view,name='education_info'),
    url(r'^work_info/$',views.work_info_view,name='work_info'),
]

duals/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

urlpatterns=[
    url(r'^$',views.show_dualmessages,name='show_dualmessages'),
    url(r'^provience=(?P<pro>[0-9]+)/$',views.show_dualmessages_filter,name='show_dualmessages_filter'),
    url(r'^user_dual/$',views.show_userdual,name='show_userdual'),
    url(r'^user_dual/(?P<pk>[0-9]+)/$',views.user_dualUpdate.as_view(),name='user_dualUpdate'),
]

jobs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views
from cv.views import partpdf,interviewpdf
urlpatterns = [
    url(r'^admin/cv/base_info/partpdf/(?P<id>[0-9]+)/$',partpdf,name='partpdf'),
    url(r'^admin/cv/base_info/interviewpdf/(?P<id>[0-9]+)/$',interviewpdf,name='interviewpdf'),
    url(r'^admin/', admin.site.urls),
    url(r'^duals/',include('duals.urls',namespace='duals')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^cv/',include('cv.urls',namespace='cv')),
    url(r'^interview/',include('interview.urls',namespace='interview')),
    url(r'^schools-autocomplete/$',views.schoolsAutocomplete.as_view(),name='schools-autocomplete'),
    url(r'^position_category-autocomplete/$',views.position_categoryAutocomplete.as_view(),name='position_category-autocomplete'),
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#This is not suitable for production use!
admin.site.site_header = '招聘系统后台管理'

duals/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
from accounts.models import provience
from django.template.defaultfilters import default
class schools(models.Model):
    name=models.CharField('学校名称',max_length=30)
    pc=models.CharField('批次',max_length=10)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='高校'
        verbose_name_plural='高校管理'
status_choices=(
    ('1','未报名'),
    ('2','已报名'),
    ('3','学校审核通过'),
    ('4','学校审核未通过'),
    )
class dualmessages(models.Model):
    name=models.CharField('双选会名称',max_length=100)
    school=models.ForeignKey(schools,on_delete=models.CASCADE,verbose_name='主办高校')
    update_time=models.DateTimeField('更新日期',auto_now_add=True)
    deadline=models.DateField('报名截止日期',null=True,blank=True)
    preferred_date=models.DateTimeField('举办日期',null=True,blank=True)
    provience=models.ForeignKey(provience,verbose_name='省份')
    address=models.CharField('举办地址',max_length=100,null=True,blank=True)
    url_adress=models.CharField('链接',max_length=200,null=True,blank=True)
    cost=models.PositiveSmallIntegerField('报名费',null=True,blank=True)
    post=models.CharField('状态',max_length=1,choices=status_choices,default='1')
    person_attend=models.CharField('参加人',max_length=20,null=True,blank=True)
    cv_num=models.PositiveSmallIntegerField('简历数',null=True,blank=True)
    ks=models.NullBooleanField('是否跨省')
    comment=models.CharField('备注',max_length=100,null=True,blank=True)
    
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='双选会信息'
        verbose_name_plural='双选会信息管理'
class user_dual(models.Model):
    cuser=models.ForeignKey(User)
    dual=models.ForeignKey(dualmessages,verbose_name='双选会名称')
    dual_status=models.CharField('状态',max_length=1,choices=(('a','未报名'),('b','审核中'),('c','审核通过'),('d','已参加'),('e','活动取消'),('f','其它'),),null=True,blank=True)
    person_attend=models.CharField('参加人',max_length=20,null=True,blank=True)
    comment=models.CharField('备注',max_length=100,null=True,blank=True)
    def __str__(self):
        return self.cuser.username
    def get_absolute_url(self):
        return reverse('user_dual-detail', kwargs={'pk': self.pk})
    class Meta:
        verbose_name='用户双选会信息'
        verbose_name_plural='用户双选会信息管理'

duals/forms.py
#coding: UTF-8
'''
Created on 2017年8月12日

@author: Fu Yingbin, 浮颖彬
'''
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .models import *
from dal import autocomplete

class dualmessagesForm(ModelForm):
    class Meta:
        model = dualmessages
        exclude=['update_time']
        widgets = {
            'school':autocomplete.ModelSelect2(url='schools-autocomplete'),
        }

duals/views.py
from django.shortcuts import render,redirect,get_object_or_404

# Create your views here.
from .models import *
from .forms import *
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import authenticate, login




num_each_page=30
def show_dualmessages(request):
    proviences = provience.objects.all()
    mes_list = dualmessages.objects.filter(post=True).order_by('-update_time')
    paginator = Paginator(mes_list, num_each_page)
    page = request.GET.get('page')
    try:
        mes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        mes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        mes = paginator.page(paginator.num_pages)
    if request.method=="POST":
        if request.user.is_authenticated:
            check_box_list=request.POST.getlist('check_box_list')
            if check_box_list:
                num_add=0
                for check in check_box_list:
                    user_dual_exit=user_dual.objects.filter(dual=dualmessages.objects.get(pk=check))
                    if not user_dual_exit:
                        user_dual.objects.create(cuser=request.user,dual=dualmessages.objects.get(pk=check))
                        num_add+=1
                warning_message='{0}条信息成功添加至我的双选会！'.format(num_add)
                return render(request, 'duals\show_dualmessages.html', locals())
            else:
                warning_message = '请至少勾选一条信息！'
                return render(request, 'duals\show_dualmessages.html', locals())
        else:
            warning_message = '请先登录！'
            return render(request, 'duals\show_dualmessages.html', locals())

    else:
        warning_message=''
        return render(request, 'duals\show_dualmessages.html', locals())
def show_dualmessages_filter(request,pro):
    proviences = provience.objects.all()
    if pro:
        mes_list = dualmessages.objects.filter(post=True).filter(provience=pro).order_by('-update_time')
    else:
        mes_list = dualmessages.objects.filter(post=True).order_by('-update_time')
    paginator = Paginator(mes_list, num_each_page)
    page = request.GET.get('page')
    try:
        mes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        mes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        mes = paginator.page(paginator.num_pages)
    if request.method == "POST":
        if request.user.is_authenticated:
            check_box_list = request.POST.getlist('check_box_list')
            if check_box_list:
                num_add = 0
                for check in check_box_list:
                    try:
                        user_dual.objects.create(cuser=request.user, dual=dualmessages.objects.get(pk=check))
                        num_add += 1
                    except:
                        pass
                warning_message = '{0}条信息成功添加至我的双选会！'.format(num_add)
                return render(request, 'duals\show_dualmessages.html', locals())
            else:
                warning_message = '请至少勾选一条信息！'
                return render(request, 'duals\show_dualmessages.html', locals())
        else:
            warning_message = '请先登录！'
            return render(request, 'duals\show_dualmessages.html', locals())

    else:
        warning_message = ''
        return render(request, 'duals\show_dualmessages.html', locals())
def show_userdual(request):
    if request.user.is_authenticated:
        mes_list=user_dual.objects.filter(cuser=request.user).order_by('-dual__preferred_date')
        paginator = Paginator(mes_list, num_each_page)
        page = request.GET.get('page')
        try:
            mes = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            mes = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            mes = paginator.page(paginator.num_pages)
        return render(request, 'duals\show_userdual.html', locals())
    else:
        warning_message = '请先登录！'
        return render(request, 'duals\show_userdual.html', locals())
class user_dualUpdate(UpdateView):
    models=user_dual
    fields=['dual','dual_status','person_attend','comment']

    def get_queryset(self):
        return user_dual.objects.filter(pk=self.kwargs['pk'])

    def form_valid(self, form):
        self.object = form.save()
        return redirect('show_userdual')

duals/templates/duals/base.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>国航员工服务中心线上服务系统 </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static "css/main.css" %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static "js/hover.zoom.js" %}"></script>
    <script src="{% static "js/hover.zoom.conf.js" %}"></script>
    <link rel="shortcut icon" href="{% static "media/favicon.ico" %} ">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style type-'text/css'>
        body{margin:0 padding:0;}
        #left{width:90%;min-height:200px;float:left;}
        #right{width:10%;min-height:200px;background-color:#EEEEEE;float:left;}
    </style>
  </head>
    <body>

    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/duals">国航员工服务中心线上服务系统</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/duals/login">{% if user.is_authenticated %}你好, {{ user.username }}{% else %} 登录 {% endif %}</a></li>
            <li><a href="/duals/logout">登出</a></li>
            <li><a href="/duals/change_pass">修改密码</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  {% block content %}{% endblock %}
  <div id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <h4>国航员工服务中心</h4>
                    <p>
                        国航总部大楼西段<br/>
                        010-61463333 <br/>
                        前台
                    </p>
                </div><!-- /col-lg-4 -->
                
                <div class="col-lg-4">
                    <h4>友情链接</h4>
                    <p>
                        <a href="http://intranet.airchina.com.cn">国航门户</a><br/>
                    </p>
                </div><!-- /col-lg-4 -->
                
                <div class="col-lg-4">
                    <h4>关于员服</h4>
                    <p>国航员工服务中心为集团和公司员工提供人事行政类、商务类、综合保障类和财务类服务，共计97项服务内容，详细业务流程可电话咨询前台。</p>
                </div><!-- /col-lg-4 -->
            
            </div>
        
        </div>
    </div>
    

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

duals/templates/duals/show_dualmessages.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}

  <div align="center" class="container pt">
  	<div align="left"><p> 欢迎使用！</p></div>
  	<form action='' method='POST'>{% csrf_token %}
	<div id='left'>
	<table border="1">
	<tr>
	<td>双选会名称</td>
	<td>省份</td>
	<td>主办高校/机构</td>
	<td>更新日期</td>
	<td>报名截止日期</td>
	<td>举办日期</td>
	<td>举办地址</td>
	<td>选择</td>
	</tr>
	{% for m in mes%}
		<tr> 
			<td><a href="{{m.url_adress}}" target="_black">{{m.name}}</a></td>
			<td>{{m.provience}}</td>
			<td>{{m.school }}</td>
			<td>{{m.update_time |date:"Y-m-d H:i:s" }}</td>
			<td>{{m.deadline|date:"Y-m-d" }}</td>
			<td>{{m.preferred_date|date:"Y-m-d H:i:s"}}</td>
			<td>{{m.address}}</td>
			<td><input type='checkbox' value='{{m.id}}' name='check_box_list'/>
		</tr>
	{%endfor%}
	</table>
	<br/>
	<input type='submit' value='添加到我的双选会信息'/>
	</div>
	</form>
	<div id='right'>
		<p>按照省份筛选</p>
		{% for pro in proviences %}

			<a href="provience={{pro.id}}">{{pro.name}}</a><br/>
		{% endfor %}
	</div>

	<div class="pagination">
    	<span class="step-links">
        	{% if mes.has_previous %}
           		<a href="?page={{ mes.previous_page_number }}">previous</a>
        	{% endif %}
 
        	<span class="current">
           	 	Page {{ mes.number }} of {{ mes.paginator.num_pages }}.
        	</span>
 
        	{% if mes.has_next %}
            	<a href="?page={{ mes.next_page_number }}">next</a>
        	{% endif %}
    	</span>
	</div>
  </div>
{% endblock %}

duals/templates/duals/show_userdual.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}

  <div align="center" class="container pt">
  	<div align="left"><font color="#02DF82"> {{warning_message}}</font></div>
  	<br/>
	<div>
	<table border="1">
	<tr>
	<td>双选会名称</td>
	<td>省份</td>
	<td>主办高校/机构</td>
	<td>报名截止日期</td>
	<td>举办日期</td>
	<td>举办地址</td>
	<td>状态</td>
	<td>参加人</td>
	<td>备注</td>
	<td>修改</td>
	</tr>
	{% for m in mes%}
		<tr> 
			<td><a href="{{m.dual.url_adress}}" target="_black">{{m.dual.name}}</a></td>
			<td>{{m.dual.provience }}</td>
			<td>{{m.dual.school }}</td>
			<td>{{m.dual.deadline|date:"Y-m-d" }}</td>
			<td>{{m.dual.preferred_date|date:"Y-m-d H:i:s"}}</td>
			<td>{{m.dual.address}}</td>
			<td>{% if m.dual_status %}{{m.get_dual_status_display}}{%else%}{%endif%}</td>
			<td>{%if m.person_attend%}{{m.person_attend}}{%else%}{%endif%}</td>
			<td>{%if m.comment%}{{m.comment}}{%else%}{%endif%}</td>
			<td><a href='/duals/user_dual/{{m.id}}'>修改</a></td>
		</tr>
	{%endfor%}
	</table>

	</div>
	
	

	<div class="pagination">
    	<span class="step-links">
        	{% if mes.has_previous %}
           		<a href="?page={{ mes.previous_page_number }}">previous</a>
        	{% endif %}
 
        	<span class="current">
           	 	Page {{ mes.number }} of {{ mes.paginator.num_pages }}.
        	</span>
 
        	{% if mes.has_next %}
            	<a href="?page={{ mes.next_page_number }}">next</a>
        	{% endif %}
    	</span>
	</div>
  </div>
{% endblock %}

duals/templates/duals/user_dual_form.html
{% extends "base.html" %}
{% load  staticfiles %}
{% block content %}

<div class="container pt">
	<form action="{{path}}" method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update" />
	</form>
</div>
{% endblock %}