accounts/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^login/$',views.my_login,name='login'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^change_password/$',views.change_pass,name='change_pass'),
    url(r'^forget_password/$',views.forget_password,name='forget_password'),
]

cv/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

urlpatterns=[
    url(r'^base_info/$',views.base_info_view,name='base_info_no_para'),
    url(r'^base_info/(?P<id>[0-9]+)/(?P<pro>[0-9]+)/$',views.base_info_view,name='base_info'),
    url(r'^education_info/$',views.education_info_view,name='education_info'),
    url(r'^work_info/$',views.work_info_view,name='work_info'),
]

interview/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^process/$',views.show_process,name='show_process'),
    url(r'^getPoints/(?P<cho>[0-9]+)/$',views.getPoints,name='getPoints'),
    url(r'^getHelpMessage/(?P<point>[0-9]+)/$',views.getHelpMessage,name='getHelpMessage'),
]

jobs/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from . import views
from cv.views import partpdf,interviewpdf
urlpatterns = [
    url(r'^admin/cv/base_info/partpdf/(?P<id>[0-9]+)/$',partpdf,name='partpdf'),
    url(r'^admin/cv/base_info/interviewpdf/(?P<id>[0-9]+)/$',interviewpdf,name='interviewpdf'),
    url(r'^admin/', admin.site.urls),
    url(r'^duals/',include('duals.urls',namespace='duals')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^post/',include('post.urls',namespace='post')),
    url(r'^cv/',include('cv.urls',namespace='cv')),
    url(r'^interview/',include('interview.urls',namespace='interview')),
    url(r'^schools-autocomplete/$',views.schoolsAutocomplete.as_view(),name='schools-autocomplete'),
    url(r'^position_category-autocomplete/$',views.position_categoryAutocomplete.as_view(),name='position_category-autocomplete'),
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)#This is not suitable for production use!
admin.site.site_header = '招聘系统后台管理'

post/urls.py
# urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.show_positions,name='show_positions'),
    url(r'^property=(?P<pro>[a-z]+)$', views.show_positions,name='show_positions'),
    url(r'^category=(?P<cat>[0-9]+)$', views.show_positions,name='show_positions'),
    url(r'^category=(?P<cat>[0-9]+)property=(?P<pro>[a-z]+)$', views.show_positions,name='show_positions'),
    #url(r'^property=(?P<pro>[a-z]+)/category=(?P<cat>[0-9]+)$', views.show_positions,name='show_positions'),
    url(r'^(?P<id>[0-9]+)/$',views.show_proviences,name='show_pro'),
    url(r'^(?P<id>[0-9]+)/(?P<pro>[0-9]+)/$',views.to_cv,name='to_cv'),
]

templates/base.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="zh-cmn-Hans">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>**公司招聘门户</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/jquery.step.css" %}" rel="stylesheet">

    <script src="{% static "js/jquery.min.js"%}"></script>
    <script src="{% static "js/jquery.step.min.js"%}"></script>

    <!-- Custom styles for this template -->
    <link href="{% static "css/main.css" %}" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static "js/hover.zoom.js" %}"></script>
    <script src="{% static "js/hover.zoom.conf.js" %}"></script>

    <script src="{% static "js/jquery.min.js"%}"></script>
    <script src="{% static "js/jquery.step.min.js"%}"></script>
    <link rel="shortcut icon" href="/media/favicon.ico "/>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style type-'text/css'>
        ul li{  list-style-type:none;  }
        li.error {color:red;}
        li.warning {color:#FF8000;}
        li.success {color:#0000FF;}
        li.info {color:#01DF01;}
        body{margin:0 padding:0;}
        .main {width: 1000px;margin: 100px auto;}
        .errorlist{color:red;}
        #step { margin-bottom: 60px;}
    </style>

  </head>
    <body>
    <!-- Static navbar -->
    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'post:show_positions' %}">**公司招聘门户</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/accounts/signup/?next={{request.path}}">注册</a></li>
            <li><a href="/accounts/login/?next={{request.path}}">{% if user.is_authenticated %}你好, {{ user.username }}{% else %} 登录 {% endif %}</a></li>
            <li><a href="{% url 'interview:show_process' %}">我的进度</a></li>
            <li><a href="{% url 'cv:base_info_no_para' %}">我的简历</a></li>
            <li><a href="{% url 'accounts:logout' %}">登出</a></li>
            <li><a href="{% url 'accounts:change_pass' %}">修改密码</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
        <p>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </p>
    </div>
    <br/>
  {% block content %}{% endblock %}
  <div id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <h4>中公教育</h4>
                    <p><font size='2'>
                        **科技股份有限公司，是国内民办教育知名品牌“**公司”的主要实体。**公司拥有全国31个省市，近350个地市，470家直营分部，近6000人专职教师团队，在职员工10000余人。10余个考试项目，4500余种培训课程，3000余种教辅类图书，每年培训学员超过100万，图书用户超过1000万。</font>
                    </p>
                </div><!-- /col-lg-4 -->

                <div class="col-lg-4">
                    <h4>联系方式</h4>
                    <p><font size='2'>
                        师资类：m<br/>
                        招聘专线：<br/>
                        网络营销类 <br/>
                        招聘专线：010-6095****
                        </font>
                    </p>
                </div><!-- /col-lg-4 -->

                <div class="col-lg-4">
                    <h4>友情链接</h4>
                    <p><font size='2'><a href="http://www.offcn.com">***</a></font><br/></p>
                </div><!-- /col-lg-4 -->

            </div>

        </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>